#!/bin/bash

# Default to .env.production if no argument is provided
ENV_FILE=${1:-.env.dev}

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found!"
  exit 1
fi

echo "Loading variables from $ENV_FILE..."

# Safely evaluate and export variables from the env file
# This skips comments and blank lines
export $(grep -v '^#' "$ENV_FILE" | xargs)

# Run the docker build using the exported variables
docker build \
  --build-arg NEXT_PUBLIC_ANALYTICS_ENDPOINT="$NEXT_PUBLIC_ANALYTICS_ENDPOINT" \
  --build-arg NEXT_PUBLIC_ANALYTICS_WRITE_KEY="$NEXT_PUBLIC_ANALYTICS_WRITE_KEY" \
  --build-arg NEXT_PUBLIC_ALLOW_DESKTOP_TESTING="$NEXT_PUBLIC_ALLOW_DESKTOP_TESTING" \
  --build-arg NEXT_PUBLIC_WHATSAPP_NUMBER="$NEXT_PUBLIC_WHATSAPP_NUMBER" \
  --build-arg NEXT_PUBLIC_SERVICE_SALES_INVOICE="$NEXT_PUBLIC_SERVICE_SALES_INVOICE" \
  --build-arg NEXT_PUBLIC_SERVICE_CREDIT_NOTE="$NEXT_PUBLIC_SERVICE_CREDIT_NOTE" \
  --build-arg NEXT_PUBLIC_SERVICE_BUYER_INITIATED_INVOICES="$NEXT_PUBLIC_SERVICE_BUYER_INITIATED_INVOICES" \
  --build-arg NEXT_PUBLIC_SERVICE_NIL_FILING="$NEXT_PUBLIC_SERVICE_NIL_FILING" \
  --build-arg NEXT_PUBLIC_SERVICE_MRI="$NEXT_PUBLIC_SERVICE_MRI" \
  --build-arg NEXT_PUBLIC_SERVICE_TOT="$NEXT_PUBLIC_SERVICE_TOT" \
  --build-arg NEXT_PUBLIC_SERVICE_ITR="$NEXT_PUBLIC_SERVICE_ITR" \
  --build-arg NEXT_PUBLIC_SERVICE_PIN_REGISTRATION="$NEXT_PUBLIC_SERVICE_PIN_REGISTRATION" \
  --build-arg NEXT_PUBLIC_SERVICE_ESLIP="$NEXT_PUBLIC_SERVICE_ESLIP" \
  --build-arg NEXT_PUBLIC_SERVICE_NITA="$NEXT_PUBLIC_SERVICE_NITA" \
  --build-arg NEXT_PUBLIC_SERVICE_AHL="$NEXT_PUBLIC_SERVICE_AHL" \
  --build-arg NEXT_PUBLIC_SERVICE_TCC_APPLICATION="$NEXT_PUBLIC_SERVICE_TCC_APPLICATION" \
  --build-arg NEXT_PUBLIC_SERVICE_PIN_RETRIEVE="$NEXT_PUBLIC_SERVICE_PIN_RETRIEVE" \
  --build-arg NEXT_PUBLIC_SERVICE_PIN_CHECK="$NEXT_PUBLIC_SERVICE_PIN_CHECK" \
  --build-arg NEXT_PUBLIC_SERVICE_STAFF_CHECK="$NEXT_PUBLIC_SERVICE_STAFF_CHECK" \
  --build-arg NEXT_PUBLIC_SERVICE_STATION="$NEXT_PUBLIC_SERVICE_STATION" \
  --build-arg NEXT_PUBLIC_SERVICE_IMPORT_CHECK="$NEXT_PUBLIC_SERVICE_IMPORT_CHECK" \
  --build-arg NEXT_PUBLIC_SERVICE_PAYROLL="$NEXT_PUBLIC_SERVICE_PAYROLL" \
  -t ghcr.io/chatnationwork/tax-app:latest \
  -t ghcr.io/chatnationwork/tax-app:0.1.1 . 

